[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm --filter web build"]

[start]
cmd = "cd apps/web && npx serve -s build -l $PORT"
