[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --filter @gns/web --filter @gns/api-web --ignore-scripts"]

[phases.build]
cmds = ["pnpm --filter @gns/web build"]

[start]
cmd = "cd apps/web && npx serve -s build -l $PORT"
